# placement
# XXX geometry do not seem to work on wayland
#geometry=70%x70%+100+200
autofit=70%

# hw
vo=gpu
hwdec=vaapi

# sound
ao=pulse
volume=70
volume-max=150
audio-channels=stereo
audio-pitch-correction=yes
audio-normalize-downmix=yes

# divers
cache=auto
log-file=~/.config/mpv/mpv.log
#cache-default=8192
#save-position-on-quit
script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp
ytdl=yes
ytdl-format=av1/bestvideo[height<=?1080]+bestaudio/best
# For some reason youtube block the download in ipv6...
#ytdl-raw-options=force-ipv4=
user-agent="Mozilla/5.0 (Windows NT 10.0; WOW64; rv:98.0) Gecko/20100101 Firefox/98.0"

#video-sync=display-resample
#scale=ewa_lanczossharp
#cscale=ewa_lanczossoft
#dscale=mitchell
#scale-antiring=0.7
#cscale-antiring=0.7
#dither-depth=auto
#interpolation=yes
#correct-downscaling=yes
#sigmoid-upscaling=yes
deband=no

[audio]
mute=no
force-window=no
no-video

#[protocol.http]
#vo=opengl
#force-window=immediate
#
#[protocol.https]
#vo=opengl
#force-window=immediate
