" Import bepo keyboard settings "
source $HOME/.vim/vimrc.bepo

" Auto-complete C "
set path=/usr/include,/usr/local/include,/usr/local/lib

" Divers "
set nocompatible
set modelines=0
set number
set cursorline
set noerrorbells
set incsearch
set hlsearch
set encoding=utf-8

" crypt
setlocal cm=blowfish2

" maintain undo history between sessions
set undofile
set undodir=~/.vim/undo
set noswapfile

" case insensitive search
set ignorecase
set smartcase
set infercase

set shell=/bin/bash
set undolevels=1000
filetype off

" " Vundle "
set rtp+=$HOME/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle manage itself "
Plugin 'gmarik/Vundle.vim'

" Other(s) plugins "
Plugin 'scrooloose/nerdtree'
let NERDTreeIgnore=['\.pyc$', '\~$'] 
map <C-n> :NERDTreeToggle<CR>
Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
set laststatus=2
set noshowmode

call vundle#end()
filetype plugin indent on

" Indent options "
set autoindent
set colorcolumn=90
set tabstop=4 shiftwidth=4 expandtab

" remove trailing whitespaces and ^M chars
autocmd FileType c,cpp,java,php,js,python,twig,xml,yml autocmd BufWritePre <buffer> :call setline(1,map(getline(1,"$"),'substitute(v:val,"\\s\\+$","","")'))

" remember cursor position
autocmd BufReadPost *
		\ if line("'\"") > 0 && line("'\"") <= line("$") |
		\ exe "normal g`\"" |
		\ endif

" Bad whitespaces "
"au BufRead, BufNewFile *.py, *.pyw, *.c, *.cpp, *.h match BadWhitespace /\s\+$/

" remapping "
nnoremap <Enter> o<ESC>
nnoremap <S-Enter> O<ESC>
nnoremap ê <ESC>:w<CR>
nnoremap Ê <ESC>:wa<CR>
nnoremap <TAB> :bn<CR>
nnoremap <S-TAB> :bp<CR>

" Enable folding "
set foldmethod=indent
set foldlevel=99
nnoremap <space> za

" For python "
let python_highlight_all=1
au BufNewFile, BufRead *.py
    \ set softtabstop=4
    \ set textwidth=79
    \ set fileformat=unix

" For latex
au BufNewFile,BufRead *.cls set filetype=tex

" Colors "
set t_Co=256
"set background=dark
colorscheme fahrenheit
hi Normal ctermbg=None
hi NonText ctermbg=None

hi ColorColumn ctermbg=256
syntax on


" Commands
" remove trailing white space
command Nows :%s/\s\+$//

" remove blank lines
command Nobl :g/^\s*$/d
