"    ▗
" ▌ ▌▄ ▛▚▀▖▙▀▖▞▀▖
" ▐▐ ▐ ▌▐ ▌▌  ▌ ▖
"  ▘ ▀▘▘▝ ▘▘  ▝▀

" first things first
set nocompatible noerrorbells
let mapleader = "à"
filetype on

source $HOME/.vim/rc/remap.vim
source $HOME/.vim/rc/plugin.vim

" auto-complete c
set path=/usr/include,/usr/local/include,/usr/local/lib

if has("cscope")
    " cscope
    set cscopeprg=/usr/bin/cscope
    set cscoperelative
    set cscopetag
    "set cst
    set csto=0
    set nocscopeverbose
    set cscopequickfix=s-,c-,d-,i-,t-,e-
endif

let s:cspfile = "cscope.out"
if filereadable(s:cspfile)
    exec "cscope add " . s:cspfile
endif

" divers
set modelines=5
set number                      " show line number
set ruler                       " show cursor position
set backspace=indent,eol,start  " powerful backspace
set showmode
set splitright splitbelow
set incsearch                   " shows the match while typing
set hlsearch                    " highlight found searches
set autoread                    " automatic read if changed file
set autowrite                   " automatic write befor :next, :make etc
set encoding=utf-8
set synmaxcol=256
set shell=/bin/bash
set showcmd "showmatch
set wildmenu
set wildignore=*.pyc,*.o
set wildignore+=*.pdf,*.psd
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png,*.tiff
set history=2047
set hidden
set ttyfast
set lazyredraw

set fileformats=unix,dos,mac    " prefer Unix over Windows over OS 9 formats

" crypt
"setlocal cm=blowfish2

" make vim to handle long lines nicely.
set wrap
set textwidth=79
set formatoptions=qrn1
"set colorcolumn=79
"hi ColorColumn ctermbg=lightgrey

" undo & backup & swap
if !has('nvim')
    " tidy
    set viminfo+=n~/.vim/viminfo
    set undofile undodir=~/.vim/undo undolevels=1000 "undoreload=1000
    set nobackup nowritebackup backupdir=~/.vim/backup
    set noswapfile
else
    " tidy
    set viminfo+=n~/.vim/nviminfo
    set undofile undodir=~/.vim/nundo undolevels=1000 "undoreload=1000
    set nobackup nowritebackup backupdir=~/.vim/backup
    set noswapfile
    set mouse=
endif
"rst

" good search
set ignorecase smartcase infercase

" indent options "
set tabstop=4 shiftwidth=4
" expandtab = spaces for tabs, noexpandtab=tabs
set expandtab
set shiftround
set autoindent
set smarttab

" completion
set complete=.,w,b,u,t,i
set completeopt=menuone,preview,longest

" folding "
"set foldmethod=indent
"set foldlevel=99
"nnoremap <space> za

" colors
" dark
colorscheme fahrenheit
" light
"colorscheme genericdc-light
syntax on

" use real tab for linux project(s) instead of spaces
autocmd BufNewFile,BufRead ~/src/linux/* set noexpandtab
autocmd BufNewFile,BufRead ~/src/linux_yke/* set noexpandtab

" (au)commands
aug wscleaning
    au!
    " remove trailing whitespaces
    au BufWritePre * silent! :%s/\s\+$//
    " remove eol blank line(s)
    au BufWritePre * silent! :%s#\($\n\s*\)\+\%$##
    " remove windows eol
    au BufWritePre * silent! :%s///g
aug end

" spelling check
aug spelling
    au!
    au filetype tex  :setlocal spell spelllang=en
    au filetype markdown :setlocal spell spelllang=en
    au filetype gitcommit  :setlocal spell spelllang=en
aug end

" pdb killer
"au FileType python au BufUnload,BufWritePre * %s/\<pdb.set_trace\>/\#pdb.set_trace/g
" <buffer> pdb.set_trace I#<esc>

aug divers
    au!
    " remember cursor position
    au BufReadPost *
       \ if line("'\"") > 0 && line("'\"") <= line("$") |
       \ exe "normal g`\"" |
       \ endif
aug end

aug cursorhighlight
    au!
    au WinLeave * set nocursorline nocursorcolumn
    au WinEnter * set cursorline cursorcolumn
aug end

aug filetypeGroup
    au!
    au BufNewFile,BufRead *.cls set filetype=tex
    au BufNewFile,BufRead *.cc set filetype=cpp
    au BufNewFile,BufRead *.patch set filetype=diff
    au BufRead,BufNewFile *.modulemap set filetype=modulemap
    au BufRead,BufNewFile *.service set filetype=systemd
    au BufRead,BufNewFile *.target set filetype=systemd
    au BufNewFile,BufRead *.nim set filetype=nim
    au BufNewFile,BufRead *.gotmpl set filetype=helm
    au BufNewFile,BufRead *.nft set filetype=nftables
    au BufNewFile,BufRead *.ign set filetype=json
    au BufNewFile,BufRead *.tftpl set filetype=yaml
    au BufNewFile,BufRead *.json5 set filetype=json
    au BufNewFile,BufRead Dockerfile* set filetype=dockerfile
    au BufNewFile,BufRead Containerfile* set filetype=dockerfile
aug end

" remove ms eol
com! Nom :%s///g

" remove trailing white space
com! Nows :%s/\s\+$//

" remove blank lines
com! Nobl :g/^\s*$/d

" cscope shortcuts
com! -nargs=1 Cfg :cs find g <args>
com! -nargs=1 Cfe :cs find e <args>
com! -nargs=1 Cft :cs find t <args>

nnoremap <leader>g :cscope find g<space>
nnoremap <leader>e :cscope find e<space>

" auto parenthesis
onoremap in( :<c-u>normal! f(vi(<cr>
onoremap il( :<c-u>normal! F)vi(<cr>


nnoremap <leader>q :call QuickfixToggle()<cr>

let g:quickfix_is_open = 0
fu! QuickfixToggle()
    if g:quickfix_is_open
        cclose
        let g:quickfix_is_open = 0
    else
        copen
        let g:quickfix_is_open = 1
    endif
endfu

aug markdown
    au!
    nnoremap <leader>p :call PreviewMd()<cr>

    fu! PreviewMd()
        "exe "silent !markdown % | lynx -stdin"
        exe "silent !markdown % | w3m -T text/html"
        "exe "silent !cat % | pandoc -f markdown_github | w3m -T text/html"
        exe "redraw!"
    endfu
aug end

" doxygen command plugin
nnoremap <leader>d :Dox<cr><esc>

aug rust_settings
    au!
    " automatic lint on write
    "au BufWritePre *.rs silent! :%! rustfmt
aug end

aug golang_settings
    au!
    " automatic lint
    "au BufWritePre *.go silent! :%! gofmt -s
    au BufRead,BufNewFile *.go set noexpandtab
    "nnoremap <leader>f :%! gofmt -s <cr><esc>
aug end

aug terraform_settings
    au!
    au BufRead,BufNewFile *.tf set filetype=hcl
    au BufRead,BufNewFile *.tf set tabstop=2 shiftwidth=2
    au BufRead,BufNewFile *.yml set tabstop=2 shiftwidth=2
    au BufRead,BufNewFile *.tfvars set filetype=hcl
    au BufRead,BufNewFile .terraformrc set filetype=hcl
    au BufRead,BufNewFile terraform.rc set filetype=hcl
    au BufRead,BufNewFile *.tfstate set filetype=json
aug end
