#!/bin/zsh

source ~/.config/bspwm/panel/panel_colors
source ~/.config/bspwm/panel/panel_config
#. mpv_functions

# check if panel is already running
if [[ $(pgrep -cx panel) -gt 1 ]]; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

# exit gracefully if terminated
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# remove old panel fifo, creat new one
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# set up bspwm to not overlap the panel
bspc config bottom_padding "$PANEL_HEIGHT"

# get bspwms status feed
bspc control --subscribe > "$PANEL_FIFO" &

# window title
# xtitle -sf 'TITLE%s' > "$PANEL_FIFO" &

# clock
while true; do
	echo -e "TIME$ICON_CLOCK$(date +"%_H:%M")"
    sleep $REFRESH_CLOCK
done > "$PANEL_FIFO" &

# date
while true; do
	echo -e "DAY$ICON_DATE$(date +'%a %d %b')"
    sleep $REFRESH_DATE
done > "$PANEL_FIFO" &

# battery
while true; do
	echo -e "BAT$(acpi -b | grep -o '[[:digit:]]\+%')"
	sleep $REFRESH_BATTERY
done > "$PANEL_FIFO" &

# external ip
while true; do
	echo -e "IP$(lynx --dump http://www.ipecho.net/plain)"
	sleep $REFRESH_EXT_IP
done > "$PANEL_FIFO" &

# dump panel into panel_bar and then into lemonbar
zsh ~/.config/bspwm/panel/panel_bar < "$PANEL_FIFO" | lemonbar -b \
    -g x"$PANEL_HEIGHT" \
    -f "$PANEL_FONT" \
    -f "$ICON_FONT" \
    -f "$ICON_FONT2" \
    -F "$COLOR_FOREGROUND" \
    -B "$COLOR_BACKGROUND" \
    -u 2 \
    | zsh &

wait
