#! /bin/sh

#bspc config border_width        		2
bspc config border						off
bspc config window_gap         			10

bspc config split_ratio         		0.5
bspc config borderless_monocle  		true
bspc config gapless_monocle     		true
bspc config focus_by_distance   		true
bspc config normal_frame_opacity		0.0
bspc config focused_frame_opacity		0.1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color 		"#282828"
bspc config focused_border_color		"#d5c4a1"
bspc config presel_border_color			"#d79921"
bspc config normal_sticky_border_color	"#1d2021"
bspc config focused_sticky_border_color	"#d5c4a1"
bspc config urgent_border_color			"#cc241d"

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a firefox desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/bspwm/panel/panel &
