series:
  settings:
    best:
      upgrade: yes
      #quality: 720p hdtv+
      target: "720p" # hdtv+"
      timeframe: 6 hours
      propers: 12 hours
    normal:
      #quality: "<=720p hdtv+"
      target: "720p" #"720p+"
      timeframe: 6 hours
      propers: 12 hours
    webrip:
       #quality: "<=720p webrip|webdl"
       target: "720p webrip|webdl"
       timeframe: 6 hours
       propers: 12 hours

  # Les séries pour lesquelles je souhaite avoir les versions en hd
  best:
    - American Horror Story
    - Mr Robot
    - Outcast
    - Supernatural
    - Game of Thrones
    - You're The Worst
    - Black Mirror
    #- Sherlock
    #- Stranger Things
    - The Knick
  # Autres séries pour lesquelles je me contente d'une résolution plus basse
  normal:
    - Rick and Morty
    - Star Wars Rebels
    #- Doctor Who (2005)
    #- Gravity Falls
    - Community
    - Scrubs
    #- South Park
    - Silicon Valley
    - The Big Bang Theory
    - American dad
    - Modern Family
    - The Simpsons
  # Pour les "web series"
  webrip:
    - House of Cards
    - Marco Polo
    #- Orange Is The New Black
